apiVersion: v1
kind: Service
metadata:
  name: gitlab-cicd-app
spec:
  selector:
    app: gitlab-cicd-app
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
